### ISSUE TITLE
Noob smashing-fields-approach-1

### ISSUE THREAD

**Issue by PFranck06** [rayman813/smashing-custom-fields#2]
Hello first thanks for smashing-fields-approach-1, i'm new in PHP so i've a noob question.
How can i display in a wordpress article a variable set in the admin panel?
for example: 'uid' => 'awesome_text_field'
Thanks

**Comment by erasmoh** [comment]
> Hello first thanks for smashing-fields-approach-1, i'm new in PHP so i've a noob question. How can i display in a wordpress article a variable set in the admin panel? for example: 'uid' => 'awesome_text_field' Thanks

You can display it with:
`$awesome_text_field = get_option('awesome_text_field');
echo $awesome_text_field; `
